### ISSUE TITLE
Can not find shaders

### ISSUE THREAD

**Issue by jimbok8** [Sjmhrp/VoidEngine#1]
I have the following error:
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
Thu Feb 22 09:14:57 GMT 2018 INFO:Use Java PNG Loader = true
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at sjmhrp.render.shader.ShaderProgram.loadShader(ShaderProgram.java:178)
	at sjmhrp.render.shader.ShaderProgram.<init>(ShaderProgram.java:59)
	at sjmhrp.render.shader.ShaderProgram.<init>(ShaderProgram.java:55)
	at sjmhrp.render.entity.EntityShader.<init>(EntityShader.java:26)
	at sjmhrp.render.shader.Shader.init(Shader.java:37)
	at sjmhrp.render.RenderHandler.init(RenderHandler.java:129)
	at sjmhrp.render.RenderHandler$1.run(RenderHandler.java:98)

I think that this is related to the lack of .glsl shader files

**Comment by Sjmhrp** [comment]
Could you tell me more about the system you were using? Were you running the released jar file, or building with the script?
